// Code generated by ent, DO NOT EDIT.

package checkinrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldUserID, v))
}

// CheckInDate applies equality check predicate on the "check_in_date" field. It's identical to CheckInDateEQ.
func CheckInDate(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldCheckInDate, v))
}

// StreakDays applies equality check predicate on the "streak_days" field. It's identical to StreakDaysEQ.
func StreakDays(v int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldStreakDays, v))
}

// RewardAmount applies equality check predicate on the "reward_amount" field. It's identical to RewardAmountEQ.
func RewardAmount(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldRewardAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNotIn(FieldUserID, vs...))
}

// CheckInDateEQ applies the EQ predicate on the "check_in_date" field.
func CheckInDateEQ(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldCheckInDate, v))
}

// CheckInDateNEQ applies the NEQ predicate on the "check_in_date" field.
func CheckInDateNEQ(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNEQ(FieldCheckInDate, v))
}

// CheckInDateIn applies the In predicate on the "check_in_date" field.
func CheckInDateIn(vs ...time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldIn(FieldCheckInDate, vs...))
}

// CheckInDateNotIn applies the NotIn predicate on the "check_in_date" field.
func CheckInDateNotIn(vs ...time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNotIn(FieldCheckInDate, vs...))
}

// CheckInDateGT applies the GT predicate on the "check_in_date" field.
func CheckInDateGT(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGT(FieldCheckInDate, v))
}

// CheckInDateGTE applies the GTE predicate on the "check_in_date" field.
func CheckInDateGTE(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGTE(FieldCheckInDate, v))
}

// CheckInDateLT applies the LT predicate on the "check_in_date" field.
func CheckInDateLT(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLT(FieldCheckInDate, v))
}

// CheckInDateLTE applies the LTE predicate on the "check_in_date" field.
func CheckInDateLTE(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLTE(FieldCheckInDate, v))
}

// StreakDaysEQ applies the EQ predicate on the "streak_days" field.
func StreakDaysEQ(v int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldStreakDays, v))
}

// StreakDaysNEQ applies the NEQ predicate on the "streak_days" field.
func StreakDaysNEQ(v int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNEQ(FieldStreakDays, v))
}

// StreakDaysIn applies the In predicate on the "streak_days" field.
func StreakDaysIn(vs ...int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldIn(FieldStreakDays, vs...))
}

// StreakDaysNotIn applies the NotIn predicate on the "streak_days" field.
func StreakDaysNotIn(vs ...int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNotIn(FieldStreakDays, vs...))
}

// StreakDaysGT applies the GT predicate on the "streak_days" field.
func StreakDaysGT(v int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGT(FieldStreakDays, v))
}

// StreakDaysGTE applies the GTE predicate on the "streak_days" field.
func StreakDaysGTE(v int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGTE(FieldStreakDays, v))
}

// StreakDaysLT applies the LT predicate on the "streak_days" field.
func StreakDaysLT(v int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLT(FieldStreakDays, v))
}

// StreakDaysLTE applies the LTE predicate on the "streak_days" field.
func StreakDaysLTE(v int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLTE(FieldStreakDays, v))
}

// RewardAmountEQ applies the EQ predicate on the "reward_amount" field.
func RewardAmountEQ(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldRewardAmount, v))
}

// RewardAmountNEQ applies the NEQ predicate on the "reward_amount" field.
func RewardAmountNEQ(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNEQ(FieldRewardAmount, v))
}

// RewardAmountIn applies the In predicate on the "reward_amount" field.
func RewardAmountIn(vs ...float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldIn(FieldRewardAmount, vs...))
}

// RewardAmountNotIn applies the NotIn predicate on the "reward_amount" field.
func RewardAmountNotIn(vs ...float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNotIn(FieldRewardAmount, vs...))
}

// RewardAmountGT applies the GT predicate on the "reward_amount" field.
func RewardAmountGT(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGT(FieldRewardAmount, v))
}

// RewardAmountGTE applies the GTE predicate on the "reward_amount" field.
func RewardAmountGTE(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGTE(FieldRewardAmount, v))
}

// RewardAmountLT applies the LT predicate on the "reward_amount" field.
func RewardAmountLT(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLT(FieldRewardAmount, v))
}

// RewardAmountLTE applies the LTE predicate on the "reward_amount" field.
func RewardAmountLTE(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLTE(FieldRewardAmount, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CheckInRecord {
	return predicate.CheckInRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CheckInRecord {
	return predicate.CheckInRecord(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CheckInRecord) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CheckInRecord) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CheckInRecord) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.NotPredicates(p))
}
