// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/checkinrecord"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CheckInRecord is the model entity for the CheckInRecord schema.
type CheckInRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// CheckInDate holds the value of the "check_in_date" field.
	CheckInDate time.Time `json:"check_in_date,omitempty"`
	// StreakDays holds the value of the "streak_days" field.
	StreakDays int `json:"streak_days,omitempty"`
	// RewardAmount holds the value of the "reward_amount" field.
	RewardAmount float64 `json:"reward_amount,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CheckInRecordQuery when eager-loading is set.
	Edges        CheckInRecordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CheckInRecordEdges holds the relations/edges for other nodes in the graph.
type CheckInRecordEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CheckInRecordEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CheckInRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case checkinrecord.FieldRewardAmount:
			values[i] = new(sql.NullFloat64)
		case checkinrecord.FieldID, checkinrecord.FieldUserID, checkinrecord.FieldStreakDays:
			values[i] = new(sql.NullInt64)
		case checkinrecord.FieldCreatedAt, checkinrecord.FieldUpdatedAt, checkinrecord.FieldCheckInDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CheckInRecord fields.
func (_m *CheckInRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case checkinrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case checkinrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case checkinrecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case checkinrecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case checkinrecord.FieldCheckInDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field check_in_date", values[i])
			} else if value.Valid {
				_m.CheckInDate = value.Time
			}
		case checkinrecord.FieldStreakDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field streak_days", values[i])
			} else if value.Valid {
				_m.StreakDays = int(value.Int64)
			}
		case checkinrecord.FieldRewardAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_amount", values[i])
			} else if value.Valid {
				_m.RewardAmount = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CheckInRecord.
// This includes values selected through modifiers, order, etc.
func (_m *CheckInRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the CheckInRecord entity.
func (_m *CheckInRecord) QueryUser() *UserQuery {
	return NewCheckInRecordClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this CheckInRecord.
// Note that you need to call CheckInRecord.Unwrap() before calling this method if this CheckInRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CheckInRecord) Update() *CheckInRecordUpdateOne {
	return NewCheckInRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CheckInRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CheckInRecord) Unwrap() *CheckInRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CheckInRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CheckInRecord) String() string {
	var builder strings.Builder
	builder.WriteString("CheckInRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("check_in_date=")
	builder.WriteString(_m.CheckInDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("streak_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.StreakDays))
	builder.WriteString(", ")
	builder.WriteString("reward_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardAmount))
	builder.WriteByte(')')
	return builder.String()
}

// CheckInRecords is a parsable slice of CheckInRecord.
type CheckInRecords []*CheckInRecord
