// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/checkinrecord"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CheckInRecordUpdate is the builder for updating CheckInRecord entities.
type CheckInRecordUpdate struct {
	config
	hooks    []Hook
	mutation *CheckInRecordMutation
}

// Where appends a list predicates to the CheckInRecordUpdate builder.
func (_u *CheckInRecordUpdate) Where(ps ...predicate.CheckInRecord) *CheckInRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CheckInRecordUpdate) SetUpdatedAt(v time.Time) *CheckInRecordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CheckInRecordUpdate) SetUserID(v int64) *CheckInRecordUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CheckInRecordUpdate) SetNillableUserID(v *int64) *CheckInRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCheckInDate sets the "check_in_date" field.
func (_u *CheckInRecordUpdate) SetCheckInDate(v time.Time) *CheckInRecordUpdate {
	_u.mutation.SetCheckInDate(v)
	return _u
}

// SetNillableCheckInDate sets the "check_in_date" field if the given value is not nil.
func (_u *CheckInRecordUpdate) SetNillableCheckInDate(v *time.Time) *CheckInRecordUpdate {
	if v != nil {
		_u.SetCheckInDate(*v)
	}
	return _u
}

// SetStreakDays sets the "streak_days" field.
func (_u *CheckInRecordUpdate) SetStreakDays(v int) *CheckInRecordUpdate {
	_u.mutation.ResetStreakDays()
	_u.mutation.SetStreakDays(v)
	return _u
}

// SetNillableStreakDays sets the "streak_days" field if the given value is not nil.
func (_u *CheckInRecordUpdate) SetNillableStreakDays(v *int) *CheckInRecordUpdate {
	if v != nil {
		_u.SetStreakDays(*v)
	}
	return _u
}

// AddStreakDays adds value to the "streak_days" field.
func (_u *CheckInRecordUpdate) AddStreakDays(v int) *CheckInRecordUpdate {
	_u.mutation.AddStreakDays(v)
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *CheckInRecordUpdate) SetRewardAmount(v float64) *CheckInRecordUpdate {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *CheckInRecordUpdate) SetNillableRewardAmount(v *float64) *CheckInRecordUpdate {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *CheckInRecordUpdate) AddRewardAmount(v float64) *CheckInRecordUpdate {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CheckInRecordUpdate) SetUser(v *User) *CheckInRecordUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CheckInRecordMutation object of the builder.
func (_u *CheckInRecordUpdate) Mutation() *CheckInRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CheckInRecordUpdate) ClearUser() *CheckInRecordUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CheckInRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckInRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CheckInRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckInRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CheckInRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := checkinrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckInRecordUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CheckInRecord.user"`)
	}
	return nil
}

func (_u *CheckInRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkinrecord.Table, checkinrecord.Columns, sqlgraph.NewFieldSpec(checkinrecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(checkinrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CheckInDate(); ok {
		_spec.SetField(checkinrecord.FieldCheckInDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StreakDays(); ok {
		_spec.SetField(checkinrecord.FieldStreakDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStreakDays(); ok {
		_spec.AddField(checkinrecord.FieldStreakDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(checkinrecord.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(checkinrecord.FieldRewardAmount, field.TypeFloat64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkinrecord.UserTable,
			Columns: []string{checkinrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkinrecord.UserTable,
			Columns: []string{checkinrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkinrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CheckInRecordUpdateOne is the builder for updating a single CheckInRecord entity.
type CheckInRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CheckInRecordMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CheckInRecordUpdateOne) SetUpdatedAt(v time.Time) *CheckInRecordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CheckInRecordUpdateOne) SetUserID(v int64) *CheckInRecordUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CheckInRecordUpdateOne) SetNillableUserID(v *int64) *CheckInRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCheckInDate sets the "check_in_date" field.
func (_u *CheckInRecordUpdateOne) SetCheckInDate(v time.Time) *CheckInRecordUpdateOne {
	_u.mutation.SetCheckInDate(v)
	return _u
}

// SetNillableCheckInDate sets the "check_in_date" field if the given value is not nil.
func (_u *CheckInRecordUpdateOne) SetNillableCheckInDate(v *time.Time) *CheckInRecordUpdateOne {
	if v != nil {
		_u.SetCheckInDate(*v)
	}
	return _u
}

// SetStreakDays sets the "streak_days" field.
func (_u *CheckInRecordUpdateOne) SetStreakDays(v int) *CheckInRecordUpdateOne {
	_u.mutation.ResetStreakDays()
	_u.mutation.SetStreakDays(v)
	return _u
}

// SetNillableStreakDays sets the "streak_days" field if the given value is not nil.
func (_u *CheckInRecordUpdateOne) SetNillableStreakDays(v *int) *CheckInRecordUpdateOne {
	if v != nil {
		_u.SetStreakDays(*v)
	}
	return _u
}

// AddStreakDays adds value to the "streak_days" field.
func (_u *CheckInRecordUpdateOne) AddStreakDays(v int) *CheckInRecordUpdateOne {
	_u.mutation.AddStreakDays(v)
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *CheckInRecordUpdateOne) SetRewardAmount(v float64) *CheckInRecordUpdateOne {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *CheckInRecordUpdateOne) SetNillableRewardAmount(v *float64) *CheckInRecordUpdateOne {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *CheckInRecordUpdateOne) AddRewardAmount(v float64) *CheckInRecordUpdateOne {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CheckInRecordUpdateOne) SetUser(v *User) *CheckInRecordUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CheckInRecordMutation object of the builder.
func (_u *CheckInRecordUpdateOne) Mutation() *CheckInRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CheckInRecordUpdateOne) ClearUser() *CheckInRecordUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the CheckInRecordUpdate builder.
func (_u *CheckInRecordUpdateOne) Where(ps ...predicate.CheckInRecord) *CheckInRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CheckInRecordUpdateOne) Select(field string, fields ...string) *CheckInRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CheckInRecord entity.
func (_u *CheckInRecordUpdateOne) Save(ctx context.Context) (*CheckInRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckInRecordUpdateOne) SaveX(ctx context.Context) *CheckInRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CheckInRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckInRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CheckInRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := checkinrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckInRecordUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CheckInRecord.user"`)
	}
	return nil
}

func (_u *CheckInRecordUpdateOne) sqlSave(ctx context.Context) (_node *CheckInRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkinrecord.Table, checkinrecord.Columns, sqlgraph.NewFieldSpec(checkinrecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CheckInRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkinrecord.FieldID)
		for _, f := range fields {
			if !checkinrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checkinrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(checkinrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CheckInDate(); ok {
		_spec.SetField(checkinrecord.FieldCheckInDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StreakDays(); ok {
		_spec.SetField(checkinrecord.FieldStreakDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStreakDays(); ok {
		_spec.AddField(checkinrecord.FieldStreakDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(checkinrecord.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(checkinrecord.FieldRewardAmount, field.TypeFloat64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkinrecord.UserTable,
			Columns: []string{checkinrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkinrecord.UserTable,
			Columns: []string{checkinrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CheckInRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkinrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
